options:
  shopname: "Spawner Shop"
  openmessage: '&aOpening Spawner Shop'
  signsuccess: '&3You have sucessfully created a SpawnerShop sign!'
  inventorysize: 27
  nopermission: '&aYou do not have permission to do that!'
  cooldown: 10
  cooldownmessage: '&aYou can not use that command yet!'
  currencysign: $
  reloadsuccess: '&aYou have successfully reloaded SpawnerShop!'
  prefix: '&7[&eSpawnerShop&7]'
  nomoney: '&aYou do not have enough funds!'

spawners:
  enderman:
    enabled: true
    price: 100000
  blaze: true
    enabled: true
    price: 100000
  skeleton: true
    enabled: true
    price: 100000
  zombie: true
    enabled: true
    price: 100000
  creeper: true
    enabled: true
    price: 100000
  cavespider: true
    enabled: true
    price: 100000
  spider: true
    enabled: true
    price: 100000
  wolf: true
    enabled: true
    price: 100000
  chicken: true
    enabled: true
    price: 100000
  cow: true
    enabled: true
    price: 100000
  pig: true
    enabled: true
    price: 100000
  ocelot: true
    enabled: true
    price: 100000
  mushroom: true
    enabled: true
    price: 100000
  sheep: true
    enabled: true
    price: 100000
  bat: true
    enabled: true
    price: 100000
  rabbit: true
    enabled: true
    price: 100000
  squid: true
    enabled: true
    price: 100000
  villager: true
    enabled: true
    price: 100000
  zombiepigman: true
    enabled: true
    price: 100000
  silverfish: true
    enabled: true
    price: 100000
  irongolem: true
    enabled: true
    price: 100000
  slime: true
    enabled: true
    price: 100000
  horse: true
    enabled: true
    price: 100000
  witch: true
    enabled: true
    price: 100000
  magmacube: true
    enabled: true
    price: 100000
  polarbear:
    enabled: true
    price: 100000
  endermite:
    enabled: true
    price: 100000
  evoker:
    enabled: true
    price: 100000
  guardian:
    enabled: true
    price: 100000
  shulker:
    enabled: true
    price: 100000
  husk:
    enabled: true
    price: 100000
  stray:
    enabled: true
    price: 100000
  vex:
    enabled: true
    price: 100000
  vindicator:
    enabled: true
    price: 100000
  llama:
    enabled: true
    price: 100000
  mule:
    enabled: true
    price: 100000